package com.suboch.task1.publication.tag;

/**
 *
 */
public enum BookCategory {
    ART_AND_PHOTOGRAPHY,
    BIOGRAPHY,
    BUSINESS,
    CHILDRENS,
    COMPUTING,
    CRAFTS_AND_HOBBIES,
    CRIME_AND_THRILLER,
    DICTIONARIES_AND_LANGUAGES,
    FICTION,
    FOOD_AND_DRINK,
    GRAPHIC_NOVELS_ANIME_AND_MANGA,
    HISTORY_AND_ARCHAEOLOGY,
    HOME_AND_GARDEN,
    HUMOUR,
    MEDICAL,
    MIND_BODY_SPIRIT,
    NATURAL_HISTORY,
    PERSONAL_DEVELOPMENT,
    POETRY_AND_DRAMA,
    RELIGION,
    ROMANCE,
    SCIENCE_AND_GEOGRAPHY,
    SCIENCE_FICTION_FANTASY_HORROR,
    SOCIETY_AND_SOCIAL_SCIENCE,
    SPORT,
    TEACHING_RESOURCES_AND_EDUCATION,
    TECHNOLOGY_AND_ENGINEERING,
    TRAVEL_AND_HOLIDAY_GUIDES,
    NONE
}
